// components/Fab.vue
<script setup lang="ts">
import type { IAction } from "~/types";
/// STATE ///
const props = defineProps<{
  icon: string;
  actions: IAction[];
  selected: IAction["id"];
}>();
const active = ref<boolean>(false);
const hidden = ref<boolean>(false);

let last_known_scroll_position = 0;
let ticking = false;
const threshold = 50; // in pixels
const transitionDuration = 100;

/// METHODS ///
/** hide on scroll */
const onScroll = () => {
  const scroller = document.getElementById("scroller");
  const dy = scroller.scrollTop - last_known_scroll_position;
  last_known_scroll_position = scroller.scrollTop;

  if (!ticking) {
    window.requestAnimationFrame(function () {
      active.value = false;
      if (Math.abs(dy) > threshold) {
        if (dy > 0) {
          hidden.value = true;
        } else {
          hidden.value = false;
        }
      }
      ticking = false;
    });

    ticking = true;
  }
};

function toggleActive() {
  active.value = !active.value;
}

function close() {
  active.value = false;
}

/// TRANSITION METHODS ///
function onBeforeEnter(el: HTMLElement) {
  const index = Number(el.dataset.index);
  el.style.opacity = "0";
  el.style.transform = `translateY(${index + 1}rem)`;
}

function onEnter(el: HTMLElement, done) {
  const index = Number(el.dataset.index);
  const fadeUp = [
    { transform: `translateY(${index + 1}rem)`, opacity: 0 },
    { transform: "translateY(0rem)", opacity: 1 },
  ];
  const anim = el.animate(fadeUp, {
    delay: (props.actions.length - index - 1) * transitionDuration,
    duration: transitionDuration,
    easing: "ease",
    fill: "forwards",
  });
  anim.onfinish = done;
}

function onLeave(el: HTMLElement, done) {
  const index = Number(el.dataset.index);
  const fadeDown = [
    { transform: "translateY(0rem)", opacity: 1 },
    { transform: `translateY(${index + 1}rem)`, opacity: 0 },
  ];
  const anim = el.animate(fadeDown, {
    delay: index * transitionDuration,
    duration: transitionDuration,
    easing: "ease",
    fill: "forwards",
  });
  anim.onfinish = done;
}

/// LIFECYCLE HOOKS ///
onMounted(() => {
  const scroller = document.getElementById("scroller");
  scroller.addEventListener("scroll", onScroll);
});
onUnmounted(() => {
  const scroller = document.getElementById("scroller");
  scroller.removeEventListener("scroll", onScroll);
});
</script>

<template>
  <transition name="fade">
    <div v-if="!hidden" fixed bottom-5 right-5 grid gap-5>
      <div flex="~ col" items-center gap-2>
        <TransitionGroup
          :css="false"
          @before-enter="onBeforeEnter"
          @enter="onEnter"
          @leave="onLeave"
        >
          <span
            :data-index="index"
            v-for="(action, index) in active ? actions : []"
            :key="action.id"
          >
            <button
              text="2xl"
              p-3
              outline-none
              rounded-full
              shadow
              v-if="selected"
              :bg="
                selected === action.id
                  ? 'purple-800 hover:purple-700 focus:purple-700'
                  : 'black hover:gray-900 focus:gray-900'
              "
              @click="
                () => {
                  action.callback();
                  close();
                }
              "
            >
              <div :class="action.icon" />
            </button>
          </span>
        </TransitionGroup>
      </div>
      <div class="fab" :class="{ active }" transition>
        <slot>
          <button
            @click="toggleActive()"
            bg="black hover:gray-900 focus:gray-900"
            outline-none
            p-4
            shadow
            rounded-full
          >
            <div :class="active ? 'i-mdi-close' : icon" text="2xl"></div>
          </button>
        </slot>
      </div>
    </div>
  </transition>
</template>

<style scoped>
.fab.active {
  transform: rotate(90deg);
}

.fade-enter-active,
.fade-leave-active {
  transition: transform 0.2s ease-out;
}

.fade-enter-from,
.fade-leave-to {
  transform: translateX(100%) !important;
}
</style>

// apps/web/src/components/Fab.tsx
import type { IAction } from "~/types";
import { createSpring, animated } from "solid-spring";
import {
  For,
  createSignal,
  onCleanup,
  onMount,
  Component,
  batch,
} from "solid-js";
import { TransitionStaggeredEnter } from "ui/transitions";
import _ from "lodash";

interface Props {
  icon: string;
  actions: IAction[];
  selected: IAction["id"];
  onSelect: (id: IAction["id"]) => void;
}

const Fab: Component<Props> = (props) => {
  const [width, setWidth] = createSignal<number>(0);
  const [open, setOpen] = createSignal<boolean>(false);
  const [hidden, setHidden] = createSignal<boolean>(false);

  let last_known_scroll_position = 0;
  const threshold = 30; // in pixels
  const onScroll = _.throttle((e: Event) => {
    const el = e.currentTarget as HTMLElement;
    if (!el) return;
    const dy = el.scrollTop - last_known_scroll_position;
    last_known_scroll_position = el.scrollTop;
    batch(() => {
      setOpen(false);
      if (Math.abs(dy) > threshold) {
        if (dy > 0) {
          setHidden(true);
        } else {
          setHidden(false);
        }
      }
    });
  }, 100);

  const slide = createSpring(() => ({
    to: { marginLeft: 0 },
    from: { marginLeft: -2 * width() },
    reverse: hidden(),
  }));

  onMount(() => {
    const scroller = document.getElementById("scroller");
    if (scroller)
      scroller.addEventListener("scroll", onScroll, { passive: true });
  });

  onCleanup(() => {
    const scroller = document.getElementById("scroller");
    if (scroller) scroller.removeEventListener("scroll", onScroll);
  });

  return (
    <div flex fixed bottom-0 right-0 overflow-hidden>
      <div p-5 grid gap-5>
        <div
          ref={(el) => {
            if (width()) return;
            requestAnimationFrame(function handler() {
              const style = getComputedStyle(el);
              const w = parseFloat(style.width);
              if (!w) {
                requestAnimationFrame(handler);
                return;
              }
              setWidth(w);
            });
          }}
          flex="~ col-reverse"
          items-center
          gap-2
        >
          <TransitionStaggeredEnter
            length={props.actions.length}
            duration={100}
          >
            <For each={open() ? props.actions : []}>
              {({ icon, id }, index) => (
                <button
                  data-index={index()}
                  text="2xl"
                  grid
                  place-items-center
                  h-13
                  w-13
                  outline-none
                  rounded-full
                  shadow
                  class={
                    props.selected === id
                      ? "bg-purple-800 hover:bg-purple-700 focus:bg-purple-700"
                      : "bg-gray-900 hover:bg-gray-800 focus:bg-gray-800"
                  }
                  style={{
                    transform: `translateY(100px)`,
                  }}
                  onClick={() => {
                    if (props.selected === id) return;
                    props?.onSelect(id);
                    setOpen(false);
                  }}
                >
                  <div class={icon} />
                </button>
              )}
            </For>
          </TransitionStaggeredEnter>
        </div>
        <button
          classList={{
            "rotate-90 bg-pink-800": open(),
            "bg-gray-900": !open(),
          }}
          style={{ "-webkit-tap-highlight-color": "transparent" }}
          transition-transform
          transition-colors
          outline-none
          w-15
          h-15
          shadow
          rounded-full
          onClick={() => setOpen(!open())}
        >
          <div class={open() ? "i-mdi-close" : props.icon} text="2xl"></div>
        </button>
      </div>
      <animated.div style={slide()}></animated.div>
    </div>
  );
};

export default Fab;
