// apps/web/src/components/Navbar.tsx
import { useAppState } from '~/stores'
import { useSearchParams, useLocation, useNavigate } from 'solid-start'
import {
  onMount,
  createEffect,
  createSignal,
  onCleanup,
  on,
  Show,
  Component,
} from 'solid-js'
import { createSpring, animated } from 'solid-spring'
import { TransitionFade } from 'ui/transitions'
import { throttle } from 'lodash-es'

export const Navbar: Component = () => {
  const [mounted, setMounted] = createSignal<boolean>(false)
  const [height, setHeight] = createSignal<number>(0)
  const [appState, setAppState] = useAppState()
  const [query, setQuery] = createSignal<string>('')

  const navigate = useNavigate()
  const location = useLocation()
  const [, setSearchParams] = useSearchParams()

  const showBack = () => location.pathname.startsWith('/r/')

  const toggleDrawer = () => {
    setAppState((_) => ({
      drawerVisible: !_.drawerVisible,
    }))
  }

  const navVisible = () => appState.navVisible
  const setNavVisible = (val: boolean) => {
    setAppState({
      navVisible: val,
    })
  }

  const slide = createSpring(() => ({
    from: { marginBottom: -1 * height() },
    to: { marginBottom: 0 },
    reverse: !navVisible(),
    immediate: !mounted(),
  }))

  let last_known_scroll_position = 0
  const threshold = 30 // in pixels
  const onScroll = throttle((e: Event) => {
    const el = e.currentTarget as HTMLElement
    if (!el) return
    const dy = el.scrollTop - last_known_scroll_position
    last_known_scroll_position = el.scrollTop
    if (el.scrollTop < 5) {
      setNavVisible(true)
      return
    }
    if (Math.abs(dy) > threshold) {
      if (dy > 0) {
        setNavVisible(false)
      } else {
        setNavVisible(true)
      }
    }
  }, 100)

  createEffect(
    on(
      () => location.pathname,
      () => {
        setNavVisible(true)
        const scroller = document.getElementById('scroller')
        if (!scroller) return
        scroller.addEventListener('scroll', onScroll, { passive: true })
        onCleanup(() => scroller.removeEventListener('scroll', onScroll))
      }
    )
  )

  onMount(() => {
    setMounted(true)
  })

  return (
    <div class="overflow-hidden shrink-0 z-20 relative bg-black">
      <animated.div style={slide()}></animated.div>
      <nav
        ref={(el) => {
          if (height()) return
          requestAnimationFrame(function handler() {
            const style = getComputedStyle(el)
            const h = parseFloat(style.height)
            if (!h) {
              requestAnimationFrame(handler)
              return
            }
            setHeight(h)
          })
        }}
        class="text-white flex gap-5 px-5 py-3 sticky top-0 items-center z-20 relative"
      >
        <Show
          when={!appState.isSearching}
          fallback={
            <form
              class="contents"
              onSubmit={(e) => {
                e.preventDefault()
                setSearchParams({ q: query() })
                setQuery('')
                setAppState({ isSearching: false })
              }}
            >
              <button
                type="button"
                onClick={() => setAppState({ isSearching: false })}
              >
                <span text="2xl" class="i-mdi-arrow-left"></span>
              </button>
              <input
                ref={(el) => {
                  requestAnimationFrame(() => {
                    el.focus()
                  })
                }}
                value={query()}
                onInput={(e) => setQuery(e.currentTarget.value)}
                required
                text="xl"
                grow
                bg="black"
                outline-none
              />
              <div grid class="[&_*]:grid-area-[1/-1]">
                <TransitionFade blur duration={200}>
                  <Show when={query()}>
                    <button
                      type="button"
                      onClick={() => setQuery('')}
                      onFocus={(e) => e.relatedTarget?.focus()}
                    >
                      <span text="2xl" class="i-mdi-close-circle"></span>
                    </button>
                  </Show>
                </TransitionFade>
              </div>
            </form>
          }
        >
          <button
            type="button"
            onClick={() => (showBack() ? history.go(-1) : toggleDrawer())}
          >
            <span
              text="2xl"
              classList={{
                'i-mdi-menu': !showBack(),
                'i-mdi-arrow-left': showBack(),
              }}
            ></span>
          </button>
          <span text="xl" truncate>
            {appState.title || 'RedditLattice'}
          </span>
          <span class="grow" />
          {/* <TransitionFade blur duration={200}> */}
          <Show when={showBack()}>
            <button
              type="button"
              onClick={() => setAppState({ isSearching: true })}
            >
              <span text="2xl" class="i-mdi-magnify"></span>
            </button>
          </Show>
          {/* </TransitionFade> */}
        </Show>
      </nav>
    </div>
  )
}

export default Navbar

// components/Navbar.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";

/// STATE ///
const store = useStore();
const { addSearch } = store;
const { title, query, navVisible, isSearching, drawerVisible } =
  storeToRefs(store);
const searchTerm = ref<string>("");
const route = useRoute();
const searchInput = ref<HTMLInputElement>();

let scroller: HTMLElement | null;

watch(
  route,
  () => {
    nextTick().then(() => {
      navVisible.value = true;
      if (scroller) scroller.removeEventListener("scroll", onScroll);
      scroller = document.getElementById("scroller");
      if (scroller) scroller.addEventListener("scroll", onScroll);
    });
  },

  { immediate: true }
);

/// METHODS ///
/** hide on scroll */
let last_known_scroll_position = 0;
let ticking = false;
const threshold = 50; // in pixels

const onScroll = () => {
  if (!scroller) return;
  const dy = scroller.scrollTop - last_known_scroll_position;
  last_known_scroll_position = scroller.scrollTop;
  const reached_top = scroller.scrollTop === 0;

  if (!ticking) {
    requestAnimationFrame(() => {
      if (reached_top) {
        if (dy < 0) {
          navVisible.value = true;
        }
      } else if (Math.abs(dy) > threshold) {
        if (dy > 0) {
          navVisible.value = false;
        } else {
          navVisible.value = true;
        }
      }
      ticking = false;
    });

    ticking = true;
  }
};

const onSearch = () => {
  isSearching.value = true;
  requestAnimationFrame(() => {
    searchInput.value?.focus();
  });
};

const cancelSearch = () => {
  isSearching.value = false;
};

const clearSearch = () => {
  searchTerm.value = "";
  requestAnimationFrame(() => {
    const inp = document.querySelector<HTMLInputElement>(".search-field input");
    if (!inp) return;
    inp.focus();
  });
};

const search = () => {
  query.value = searchTerm.value;
  addSearch(query.value);
  isSearching.value = false;
  searchTerm.value = "";
};
</script>

<template>
  <Transition name="slide">
    <nav
      v-if="navVisible"
      bg="black"
      text="white"
      flex
      gap-5
      px-5
      py-3
      sticky
      top-0
      items-center
      z-20
    >
      <template v-if="!isSearching">
        <button
          type="button"
          @click="
            !route.path.startsWith('/r/')
              ? (drawerVisible = !drawerVisible)
              : $router.push({ path: '/' })
          "
          :class="
            !route.path.startsWith('/r/') ? 'i-mdi-menu' : 'i-mdi-arrow-left'
          "
          text="2xl"
        ></button>
        <span text="xl" truncate>
          {{ title }}
        </span>
        <span class="grow" />
      </template>
      <form @submit.prevent="search" contents>
        <template v-if="isSearching">
          <button
            @click="cancelSearch"
            text="2xl white"
            outline-none
            class="i-mdi-arrow-left"
            type="button"
          ></button>
          <input
            ref="searchInput"
            text="xl"
            grow
            bg="black"
            outline-none
            v-model="searchTerm"
          />
        </template>
        <div grid class="wrap-btns">
          <Transition name="fade">
            <template v-if="route.path.startsWith('/r/')">
              <template v-if="isSearching">
                <button
                  type="button"
                  @click="clearSearch"
                  text="2xl"
                  class="i-mdi-close-circle"
                ></button>
              </template>
              <template v-else>
                <button
                  type="button"
                  @click="onSearch"
                  text="2xl"
                  class="i-mdi-magnify"
                ></button>
              </template>
            </template>
          </Transition>
        </div>
      </form>
    </nav>
  </Transition>
</template>

<style scoped>
.wrap-btns {
  display: grid;
}
.wrap-btns > * {
  grid-area: 1/-1;
}
.slide-enter-active,
.slide-leave-active {
  transition: all 0.3s cubic-bezier(0.86, 0, 0.07, 1);
}

.slide-enter-from,
.slide-leave-to {
  transform: translateY(-100%) !important;
}

.fade-enter-active,
.fade-leave-active {
  transition: all 0.2s ease-in;
}

.fade-enter-from,
.fade-leave-to {
  transform: rotate(180deg);
  /* opacity: 0; */
}
</style>
