// components/InfiniteLoading.vue
<script setup lang="ts">
import { Ref } from "vue";
export type State = "idle" | "error" | "loading" | "completed";
export type InfiniteState = Ref<State>;

const props = withDefaults(
  defineProps<{
    distance?: number;
    target?: string;
    firstload?: boolean;
    key?: string;
  }>(),
  {
    key: "",
    distance: 0,
    target: "body",
    firstload: true,
  }
);

const emit = defineEmits<{
  (e: "infinite", $state: typeof state, firstload: boolean): void;
}>();

const state = ref<State>("idle");

watch(
  () => props.key,
  (value) => {
    setup();
  }
);

const onScroll = () => {
  if (state.value !== "idle") return;
  const scrollArea = document.querySelector(props.target);
  if (!scrollArea) return;
  const dy =
    scrollArea.scrollHeight - scrollArea.scrollTop - scrollArea.clientHeight;
  if (dy <= props.distance) load();
};

const load = (firstload: boolean = false) => {
  state.value = "loading";
  emit("infinite", state, firstload);
};

const setup = () => {
  if (props.firstload) load(true);
};

onMounted(() => {
  nextTick().then(() => {
    const scrollArea = document.querySelector(props.target);
    if (!scrollArea) return;
    scrollArea.addEventListener("scroll", onScroll);
    setup();
  });
});

onUnmounted(() => {
  const scrollArea = document.querySelector(props.target);
  if (!scrollArea) return;
  scrollArea.removeEventListener("scroll", onScroll);
});
</script>

<template>
  <div v-if="state === 'idle'"><slot name="idle" :load="load"></slot></div>
  <div v-if="state === 'error'"><slot name="error" :retry="load"></slot></div>
  <div v-if="state === 'loading'"><slot name="loading"></slot></div>
  <div v-if="state === 'completed'"><slot name="completed"></slot></div>
</template>

// packages/ui/InfiniteLoading.tsx
import { throttle } from 'lodash-es'
import {
  Component,
  createEffect,
  createSignal,
  JSXElement,
  mergeProps,
  on,
  onCleanup,
  onMount,
} from 'solid-js'

export type State = 'idle' | 'error' | 'loading' | 'completed'
export type InfiniteHandler = (
  setState: (state: State) => void,
  firstload: boolean
) => void

interface Props {
  children: (state: State, load: (firstload?: boolean) => void) => JSXElement
  distance?: number
  target?: string
  firstload?: boolean
  key?: string
  onInfinite: InfiniteHandler
}

export const InfiniteLoading: Component<Props> = (props: Props) => {
  const merged = mergeProps(
    { key: '', distance: 0, target: 'body', firstload: true },
    props
  )

  const { onInfinite } = props

  const [state, setState] = createSignal<State>('idle')

  const onScroll = throttle((e: Event) => {
    if (state() !== 'idle') return

    const scrollTarget = document.querySelector(merged.target)
    if (!scrollTarget)
      throw new Error(
        `scroll-target ${props.target} not found for infinite loading`
      )

    const scrollBottom = Math.round(
      scrollTarget.scrollHeight -
        scrollTarget.scrollTop -
        scrollTarget.clientHeight
    )
    if (scrollBottom - 1 <= merged.distance) load()
  }, 16)

  const updateState = (newState: State) => {
    if (newState !== 'idle') {
      setState(newState)
      return
    }

    const scrollTarget = document.querySelector(merged.target)
    if (!scrollTarget)
      throw new Error(
        `scroll-target ${props.target} not found for infinite loading`
      )

    const noScrollbar = scrollTarget.scrollHeight === scrollTarget.clientHeight
    noScrollbar ? load() : setState('idle')
  }

  const load = (firstload: boolean = false) => {
    setState('loading')
    onInfinite(updateState, firstload)
  }

  const setup = () => merged.firstload && load(true)

  createEffect(
    on(
      () => merged.key,
      () => setup()
    )
  )

  onMount(() => {
    const scrollTarget = document.querySelector(merged.target)
    if (!scrollTarget)
      throw new Error(
        `scroll-target ${props.target} not found for infinite loading`
      )

    scrollTarget.addEventListener('scroll', onScroll, { passive: true })
    onCleanup(() => scrollTarget.removeEventListener('scroll', onScroll))
  })

  return <div>{props.children(state(), load)}</div>
}

export default InfiniteLoading
