// apps/web/src/routes/r/[subreddit].tsx
import { useAppState, useUserState } from '~/stores'
import { useParams, useSearchParams } from 'solid-start'
import {
  onMount,
  onCleanup,
  createEffect,
  getOwner,
  runWithOwner,
  createMemo,
  Match,
  Switch,
  batch,
} from 'solid-js'
import { IAction } from '~/types'
import ImageCard from '~/components/ImageCard'
import Fab from '~/components/Fab'
import { trpc } from '~/client'
import { Spinner, Masonry, Button, InfiniteLoading, InfiniteHandler } from 'ui'

const [appState, setAppState] = useAppState()

export default function Subreddit() {
  const componentOwner = getOwner()!
  const [userState, setUserState] = useUserState()
  const [searchParams, _] = useSearchParams()
  const params = useParams()
  const subreddit = () => params.subreddit.toLowerCase()
  const fabActions: IAction[] = [
    {
      id: 'top',
      icon: 'i-mdi-arrow-up-bold',
    },
    {
      id: 'hot',
      icon: 'i-mdi-fire',
    },
    {
      id: 'new',
      icon: 'i-mdi-new-box',
    },
  ]

  const sort = createMemo(() => userState().sort.get(subreddit()) || 'hot')

  const setSort = (sort: string) =>
    setUserState((state) => {
      state.sort.set(subreddit(), sort)
      return { ...state }
    })

  onMount(() => setSort(sort()))

  const key = createMemo(() => `${subreddit()}-${searchParams.q}-${sort()}`)

  const resetState = () => {
    batch(() => {
      setAppState(
        'title',
        searchParams.q
          ? `${searchParams.q} - /r/${subreddit()}`
          : `/r/${subreddit()}`
      )
      setAppState({
        images: {
          key: key(),
          after: '',
          data: new Set(),
        },
      })
    })
  }

  createEffect(() => appState.images.key !== key() && resetState())

  createEffect(() =>
    setUserState((state) => {
      state.subreddits.add(subreddit())
      if (searchParams.q)
        state.searchTerms.set(searchParams.q.toLowerCase(), subreddit())
      return { ...state }
    })
  )

  const onInfinite: InfiniteHandler = async (setState, firstload) => {
    if (firstload && appState.images.data.size > 0) {
      setState('idle')
      return
    }
    try {
      const ac = new AbortController()
      runWithOwner(componentOwner, () => onCleanup(() => ac.abort()))
      const { images: newImages, after } = await trpc.getImages.query(
        {
          q: searchParams.q,
          after: appState.images.after,
          subreddit: params.subreddit,
          sort: userState().sort.get(subreddit()),
          nsfw: !userState().hideNSFW,
        },
        {
          signal: ac.signal,
        }
      )
      setAppState('images', (images) => ({
        ...images,
        data: new Set([...images.data, ...newImages]),
      }))

      if (after) {
        setAppState('images', { after })
        setState('idle')
        return
      }
      setState('completed')
    } catch (e) {
      setState('error')
      throw e
    }
  }

  return (
    <div h-full max-h-full id="scroller">
      <Masonry
        items={[...appState.images.data].map((image) => ({
          id: image.name,
          data: image,
        }))}
        maxWidth={400}
        gap={userState()!.gap}
      >
        {(_, image, width) => (
          <ImageCard width={width()} image={image}></ImageCard>
        )}
      </Masonry>
      <InfiniteLoading
        onInfinite={onInfinite}
        target="#scroller"
        distance={400}
        key={appState.images.key}
      >
        {(state, load) => (
          <div class="grid p-5 place-content-center">
            <Switch>
              <Match when={state === 'idle'}>
                <Button
                  class="bg-purple-800 hover:bg-purple-700"
                  onClick={() => load()}
                >
                  Load More
                </Button>
              </Match>
              <Match when={state === 'completed'}>
                <span uppercase font-bold>
                  {appState.images.data.size > 0 ? 'END' : 'NO IMAGES FOUND'}
                </span>
              </Match>
              <Match when={state === 'error'}>
                <Button
                  onClick={() => load()}
                  class="bg-red-800 hover:bg-red-700"
                >
                  Retry
                </Button>
              </Match>
              <Match when={state === 'loading'}>
                <Spinner />
              </Match>
            </Switch>
          </div>
        )}
      </InfiniteLoading>
      <Fab
        icon="i-mdi-sort"
        actions={fabActions}
        selected={sort()}
        onSelect={(id) => setSort(id)}
      ></Fab>
    </div>
  )
}

// pages/r/[subreddit].vue
<script setup lang="ts">
import { IAction, SortType } from "~/types";
import type { InfiniteState } from "~~/components/InfiniteLoading.vue";

import { storeToRefs } from "pinia";
import { RouteLocationNormalizedLoaded } from "vue-router";
const route = useRoute();

/// STATE ///
const id = ref<boolean>(false);
const store = useStore();
const { addSubreddit } = store;
const { images, title, query, sort } = storeToRefs(store);
const fabActions = ref<IAction[]>([
  {
    id: SortType.TOP,
    icon: "i-mdi-arrow-up-bold",
    callback() {
      sort.value = SortType.TOP;
    },
  },
  {
    id: SortType.HOT,
    icon: "i-mdi-fire",
    callback() {
      sort.value = SortType.HOT;
    },
  },
  {
    id: SortType.NEW,
    icon: "i-mdi-new-box",
    callback() {
      sort.value = SortType.NEW;
    },
  },
]);
const masonryItems = computed(() =>
  images.value.data.map((image) => ({
    id: image.name,
    data: image,
  }))
);

// dynamic navbar title
watchEffect(() => {
  title.value = route.query.q
    ? `${route.query.q} - r/${route.params.subreddit}`
    : `r/${route.params.subreddit}`;
});

// flush images when sort type is changed
watch(sort, () => {
  resetState();
});

// onSearch flush images and change route
query.value = route.query.q as string;
watch(query, (q) => {
  resetState();
  navigateTo({
    path: `/r/${route.params.subreddit}`,
    query: { q },
  });
});

/// METHODS ///
const createSearchParams: () => URLSearchParams = () => {
  const searchParams = new URLSearchParams({
    subreddit: route.params.subreddit as string,
  });
  if (route.query.q) searchParams.append("q", route.query.q as string);
  if (images.value.after) searchParams.append("after", images.value.after);
  searchParams.append("sort", sort.value);
  return searchParams;
};

/** infinite loader handler */
const onInfinite = async ($state: InfiniteState, firstload: boolean) => {
  if (firstload && images.value.data.length > 0) {
    $state.value = "idle";
    return;
  }
  try {
    const { posts: newPosts, after: a } = await $fetch("/api/getImages", {
      query: Object.fromEntries(createSearchParams()),
    });
    images.value.data = [...images.value.data, ...newPosts];

    if (!a) {
      setTimeout(() => ($state.value = "completed"));
      return;
    }

    images.value.after = a;
    setTimeout(() => ($state.value = "idle"));
  } catch (e) {
    setTimeout(() => ($state.value = "error"));
  }
};

const resetState = () => {
  images.value.key = getKey(route);
  images.value.after = "";
  images.value.data = [];
  id.value = !id.value;
};

const getKey: (route: RouteLocationNormalizedLoaded) => string = (route) => {
  return `${route.params.subreddit}-${route.query.q}`;
};

/// LIFECYCLE HOOKS ///
// flush old images on mount and add subreddit to localStorage
onMounted(() => {
  if (images.value.key !== getKey(route)) resetState();
  addSubreddit(route.params.subreddit as string);
});

const { cleanUp } = onRefresh({
  callback(state) {
    resetState();
    state.set(false);
  },
});

onUnmounted(() => cleanUp());

useHead({
  title: route.query.q
    ? `${route.query.q} - r/${route.params.subreddit} - RedditLattice`
    : `r/${route.params.subreddit} - RedditLattice`,
});

definePageMeta({
  pageTransition: false,
  key: (route) => `${route.query.q}-${route.params.subreddit}`,
});
</script>

<template>
  <div max-h-full id="scroller" class="image-grid" ref="scroller">
    <Masonry
      :max-width="400"
      :items="masonryItems"
      #default="{ item: { data: image } }"
    >
      <ImageCard :image="image" />
    </Masonry>

    <InfiniteLoading
      target="#scroller"
      :distance="300"
      @infinite="onInfinite"
      :key="`${images.key}-${sort}-${id}`"
    >
      <template #idle="{ load }">
        <div p-5 grid place-content-center>
          <Button bg="purple-800 hover:purple-700" @click="load"
            >Load More</Button
          >
        </div>
      </template>
      <template #loading>
        <div grid place-content-center p-5>
          <Spinner />
        </div>
      </template>
      <template #error="{ retry }">
        <div p-5 grid place-content-center>
          <Button bg="red-800 hover:red-700" @click="retry">Retry</Button>
        </div>
      </template>
      <template #completed>
        <div p-5 grid place-content-center>
          <div font-bold tracking-wide uppercase text="sm" font="bold">
            {{ images.data.length > 0 ? "END" : "NO IMAGES FOUND" }}
          </div>
        </div>
      </template>
    </InfiniteLoading>

    <Fab icon="i-mdi-sort" :actions="fabActions" :selected="sort"> </Fab>
  </div>
</template>
